# Generated by Django 6.0.3 on 2026-03-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
