# Generated by Django 6.0.3 on 2026-03-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='mp_init_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='plano',
            field=models.CharField(default='mensal', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('pendente', 'Pendente'), ('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='trial', max_length=20),
        ),
    ]
