# Generated by Django 6.0.3 on 2026-03-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_pagamento_data_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='data_inicio',
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(default='trial', max_length=20),
        ),
    ]
