# Generated by Django 6.0.3 on 2026-03-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('duracao_minutos', models.IntegerField(default=50)),
                ('conteudo', models.TextField(blank=True)),
                ('material', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('realizada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
        ),
    ]
