# Generated by Django 6.0.3 on 2026-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='duracao_minutos',
            field=models.IntegerField(default=50),
        ),
    ]
