# Generated by Django 6.0.3 on 2026-03-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_aula_duracao_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
